### ISSUE TITLE
Possible to have action filters ignore certain methods?

### ISSUE THREAD

**Issue by joemottershaw** [daveh/php-mvc#10]
I'm assuming that currently the action filters (before/after) would apply to all the methods within the given controller? Is it possible that you could ignore certain methods or choose to assign it to a particular method or methods?

**Comment by daveh** [comment]
Yes that's right, at the moment it applies to all action methods in the controller. To only have it apply to certain methods, you'd have to first make the name of the current action available in the controller itself. This isn't currently available, but off the top of my head I would add a new property to the core controller class for the current action, e.g.

```
/** 
 * Current action
 *
 * @var string
 */
public static $current_action;
```
then in the router, in the `dispatch` method, when the controller class is created, pass this value in

```
$controller_object = new $controller($this->params);
 
$action = $this->params['action'];

$controller_object->current_action = $action;
```
so that then in the `before` method, you can check this value and only apply it to certain methods:

```
protected function before()
{
    if ($this->current_action == "index") {
        ...
    }
}
```
I haven't tested this but that's the general idea. I might add this to the framework if it fits in with the teaching. I'm updating the course at the moment so I'll see how it fits.

Does that help?

Cheers,
Dave

**Comment by joemottershaw** [comment]
That does make sense, I'm guessing you could create an array at the top of the controller containing the method names that you want the before method to run on and change the if statement to check the `current_action` is in that array or not?

I think in the long run I'd like to eventually implement it so that whenever a route is added via a post/patch/delete request, the before method is called automatically to do things like CSRF token checks and stuff, just for security reason and to help automate the development process with middleware.

I haven't actually taken your course yet so I'm probably jumping the gun a bit with both of my questions/issues I've posted! I'd probably have more understanding on how to implement all this myself ha. I've got the day off today so I'll be purchasing it shortly, especially if it's still being actively updated.

Thanks again for both your replies!

**Comment by daveh** [comment]
Yes that's it - you could have an array of methods you wanted with the before filter and just check the current action name is in it or not.

Thanks for taking the course - if you have any questions, please let me know!

Cheers,
Dave
