### ISSUE TITLE
Index controller not found

### ISSUE THREAD

**Issue by telemoes** [daveh/php-mvc#13]
Hello Daveh

I think i found a little bug..
When i do this: $router->add('{controller}/{action}');
 like $router->add('{users}/{save}');

Then i get the error index controller not found on core/routers.php line 110:
$controller = $this->params['controller'];

Thats right because in line 75 you do $params[$key] = $match; so there in no index controller then.

greetings
Martijn

**Comment by daveh** [comment]
Hi Martijn,

what URL are you trying that results in that error?

Thanks,
Dave

**Comment by telemoes** [comment]
Hi Daveh,

domain.com/public/users/create
I do in de index: $router->add('{users}/{create}');

Then i get this error

> Uncaught exception: 'ErrorException' Message: 'Undefined index: controller'

Greetings
Martijn

Edit: when i do:
$router->add('users', ['controller' => 'Users', 'action' => 'create']); it is working because index controller is exists ;)

**Comment by daveh** [comment]
Ah ok, I see the problem now. When you create a route, the controller and action have to be supplied. They can either be supplied in the parameters in the second argument of the `add` method, like this:

`$router->add('users', ['controller' => 'Users', 'action' => 'create']);`

or they can be supplied in variables in the route, like this:

`$router->add('{controller}/{action}');`

So for the first route, the URL example.com/users will match and the `createAction` method in the `Users` controller will be executed.

For the second route, the URL example.com/posts/show will match, and the `showAction` method in the `Posts` controller will be executed.

When you mentioned adding this route above:

`$router->add('{users}/{save}');`

The controller and action aren't specified, which is why you got that error. If you want a route that matches example.com/users/save, then you can do either this:

`$router->add('users/save', ['controller' => 'Users', 'action' => 'save']);`

or this:

`$router->add('{controller}/{action}');`

In both cases the `saveAction` of the `Users` controller will be executed.

Does that help?

Cheers,
Dave

**Comment by telemoes** [comment]
Hi Daveh,

I doe not understand what you mean:
When i do this
$router->add('users/save', ['controller' => 'Users', 'action' => 'save']); it is working
But when i do
$router->add('{users}/{save}'); It is not working but it is the same i think??

greetings
Martijn

**Comment by daveh** [comment]
Hi Martijn,

no, it's not the same - in a route, you can have fixed segments, like "users" and "save" in this route:

`$router->add('users/save', ['controller' => 'Users', 'action' => 'save']);`

or you can have [route variables](https://github.com/daveh/php-mvc#routing), which are contained in curly braces, like this:

`$router->add('{users}/{save}');`

This latter route defines a route with two variables. No controller or action are specified, so it's an invalid route.

Route variables can be used to add any variable you like to a route. For example, in addition to `controller` and `action`, you could add an ID variable, for example:

`$router->add('{controller}/{id:\d+}/{action}');`

This would match a URL like example.com/users/123/edit for example.

Does that help?

Cheers,
Dave

**Comment by telemoes** [comment]
Hi Daveh.

Yes it helps thx you

greetings
Martijn
