### ISSUE TITLE
How to call App\Models\User   getAll()

### ISSUE THREAD

**Issue by mbelatar** [daveh/php-mvc#30]

**Comment by daveh** [comment]
I assume you want to call this from a controller? If that's a static method, you can either call it like this:

`$users = \App\Models\User::getAll();`

(the namespace is needed because the models are in a different namespace to the controllers). Or add a `use` statement to the top of your controller class, then call the method without the namespace:

```
use App\Models\User;

class Example extends \Core\Controller
{
    public function indexAction()
    {
        $users = User::getAll();
        ...
```

**Comment by mbelatar** [comment]
It works , thank you so much
