### ISSUE TITLE
How to pass views in view data?

### ISSUE THREAD

**Issue by cinder92** [daveh/php-mvc#38]
Hello, thanks for your effort.

I'm making a helper controller, that render views for example

ControllerForm.php

```
public static function addInput($args = []){

        if(!isset($args['type'])){
            $args['type'] = 'text';
        }

        //todos los atributos recibidos en $args serán añadidos al input
        $data = ['data' => $args];
        return View::renderTemplate('templates/input.html',$data);
    }
```
i want to use that function in View:renderTemplate variables, i mean, pass a View into a data view.

Ex

```
$input = FormClass::addInput([]);

View::renderTemplate('templates/input.html',[
  'anotherView' => $input
]);
```

is this possible?

**Comment by daveh** [comment]
Yes, but you'll have to change the `renderTemplate` method in the Core\View class to return the contents of the template instead of `echo`-ing it out. For example, at the end of that method, instead of this:

`echo $twig->render($template, $args);
`

this

`return $twig->render($template, $args);
`

So as not to affect the rest of the framework, you could add a method that did this, called `getTemplate` for example, so that `renderTemplate` still uses `echo`.

Is that what you meant?

**Comment by cinder92** [comment]
Thank you @daveh  i just solved about 30 minutes ago, but yes, that is the answer. Keep it up!
