### ISSUE TITLE
Uncaught Error: Class 'Core\Router' not found 

### ISSUE THREAD

**Issue by CodeGuruKZ** [daveh/php-mvc#59]
Fatal error: Uncaught Error: Class 'Core\Router' not found in /home/islam/CodeGuru/ishop/index.php on line 10
![Screenshot from 2020-06-08 16-55-37](https://user-images.githubusercontent.com/55748958/84022945-049a2700-a9a9-11ea-903b-88b9b6847bc2.png)

AND it's what in Router 
![Screenshot from 2020-06-08 16-58-56](https://user-images.githubusercontent.com/55748958/84023134-5d69bf80-a9a9-11ea-8458-b91c38a8dad2.png)
![Screenshot from 2020-06-08 16-58-53](https://user-images.githubusercontent.com/55748958/84023136-5f338300-a9a9-11ea-8e64-16000adc787b.png)
![Screenshot from 2020-06-08 16-58-48](https://user-images.githubusercontent.com/55748958/84023138-5f338300-a9a9-11ea-8910-53a286238c18.png)

**Comment by ChrisToxz** [comment]
What is the URL you try to open?

**Comment by daveh** [comment]
It looks like you've got the index.php front controller script in the root instead of in the public folder, is that right? If so, try changing the line where you include the Composer autoloader from this:

`require dirname(__DIR__) . '/vendor/autoload.php';
`

to this:

`require __DIR__ . '/vendor/autoload.php';`

**Comment by CodeGuruKZ** [comment]
thank you very much for the help)
