### ISSUE TITLE
A function for a route path would be cool

### ISSUE THREAD

**Issue by tylunari** [daveh/php-mvc#7]
Hi, I've been looking at this code to help me learn and one thing I'd like to do is to be able to do this:
`$router->add('logout', function(){
    session_destroy();
})`

So you don't have to make a function for such a small thing.
Any ideas how to do this?

**Comment by daveh** [comment]
Hi, interesting question. To do that you'd have to change the `add` method of the Router class so that the second argument could be a function instead of an array of parameters. Then, in the body of the method, you could use [is_callable](http://php.net/manual/en/function.is-callable.php) check to see if a function had been passed, or an array of parameters as before. For example:

```
public function add($route, $action)
{
    if (is_callable($action)) {

    } else {
        // add route as before
        // ...
    }
}
```

If a function is passed, then you could do something like store it in the routing array, then in the `dispatch` method, call it when the route is matched instead of calling a controller and action.

Is that what you mean?

Having said all that, I'm not a fan of executing code like this in the routing table - I prefer to have controllers execute actions, so even though it might be more code, I think it's easier to follow what's happening when a request comes in and the controller sends a response back.

Does that help?

**Comment by tylunari** [comment]
@daveh that's exactly what I was talking about! I'll try playing around with it, thank you

**Comment by daveh** [comment]
Ah ok great - if you have any more questions, let me know!

**Comment by tylunari** [comment]
@daveh I ending getting it to work by adding 

    if(is_callable($this->params)) {
        $closeure = $this->params;
        echo $closeure();
    } else {

just below `if ($this->match($url)) {` in the `dispatch` function!

and just a quick question, how do the Models work, like how do I include them into my view/controller?

**Comment by daveh** [comment]
Looks good!

The model classes are autoloaded using Composer, so you can simply refer to them using the namespace inside a controller, e.g. for a Post class:

`$post = new \App\Models\Post();`

or if you want to have a `use` statement at the top:

```
use App\Models\Post;

$post = new Post();
```

**Comment by tylunari** [comment]
@daveh you're a legend, thanks for the help!
